### ISSUE TITLE
Attempting to access other AWS services from within the hosted lambda fails

### ISSUE THREAD

**Issue by ctartamella** [martincostello/lambda-test-server#449]
## Describe the bug

It seems that overrides in the HTTP message handling logic of the test server break calls to external AWS services when made within the Lambda.  See below for call stack and suspected cause.

## Steps To reproduce

Within a hosted Lambda, generate an SQS client object.  Use that object to send a message to a queue.

## Expected behaviour

I would expect the underlying Lambda to succeed.

## Actual behaviour
The follwing error occurs (stack truncated) when attempting to send a message to an SQS queue:

```
 Amazon.SQS.AmazonSQSException : The request has a 'X-Amzn-Trace-Id' HTTP header which is reserved for AWS X-Ray trace header and has an invalid value 'dae04c7a-6a43-4d8c-9a86-6caac024711e'
---- Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  Stack Trace:
     at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

## System information

- OS: Windows 11
- Library Version latest
- .NET version 6.0
- IDE and version Latest Rider

## Additional context

In RuntimeHandler.cs I see the follwing block I _think_ is responsible.  By definition X-Ray trace IDs are of a specific format as defined [here](https://docs.aws.amazon.com/xray/latest/devguide/xray-concepts.html#xray-concepts-traces).  

```
      // Write the response for the Lambda runtime to pass to the function to invoke
        string traceId = Guid.NewGuid().ToString();

        Logger?.LogInformation(
            "Invoking Lambda function with ARN {FunctionArn} for request Id {AwsRequestId} and trace Id {AwsTraceId}.",
            _options.FunctionArn,
            request.AwsRequestId,
            traceId);

        // These headers are required, as otherwise an exception is thrown
        httpContext.Response.Headers["Lambda-Runtime-Aws-Request-Id"] = request.AwsRequestId;
        httpContext.Response.Headers["Lambda-Runtime-Invoked-Function-Arn"] = _options.FunctionArn;

        // These headers are optional
        httpContext.Response.Headers["Lambda-Runtime-Trace-Id"] = traceId;
```

**Comment by martincostello** [comment]
Hi - thanks for the report.

In all the _known_ usage of the library to date, everything external had been mocked so the actual value of the trace ID wasn't important - it just needed to have _a_ value and be unique - a random GUID was good enough for these purposes.

Clearly this isn't appropriate if you want to use the hosted Lambda to interact with other real services.

I'll look into changing the default generation algorithm and/or adding a way to be able to customise it.

**Comment by ctartamella** [comment]
Makes total sense.  To be honest I'm not sure how the header you're setting translates to the one in the exception but I suppose it's somewhere in the Lambda runtime code.

Either way should be a simple fix.  Thanks!
________________________________

**Comment by martincostello** [comment]
Without reminding myself of the code right now, if I recall correctly it sets the value into environment variables during the execution of a single request (and reverts them at the end) because the AWS custom runtime library only fetches them out of there, so to make the simulation work properly that's needed.

I would guess that then some other AWS SDK code is seeing the environment variable set and then automatically forwarding the value on to SQS etc. in an HTTP header, which then rejects it because it's in the wrong format.

**Comment by martincostello** [comment]
Using [this documentation](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#xray-api-traceids) as a reference, from version 0.7.1 the trace ID will now be generated like this:

```csharp
var epoch = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
var buffer = RandomNumberGenerator.GetBytes(96 / 8);
var identifier = Convert.ToHexString(buffer).ToLowerInvariant();

var traceId = FormattableString.Invariant($"Root=1-{epoch:x8}-{identifier}");
```

I've validated this against the real AWS SQS service using the .NET SDK's `AmazonSQSClient.GetQueueUrlAsync(string)` method.

**Comment by martincostello** [comment]
[v0.7.1](https://www.nuget.org/packages/MartinCostello.Testing.AwsLambdaTestServer/0.7.1) containing the fix is now available from NuGet.org - thanks again for reporting this issue 🙇
